# These are some of the common functions that the metagenomics pipeline uses
# load_sample_sheet : Load the entire sample sheet generated by the gnenrate_sample_sheet.py scrip
# get_fastq_samples: Get the samples from the data directory
# get_sample_r1: Get only the forward read for a sample id
# get_sample_r2: Get only the reverse read for a sample id
# get_sample_names: Get all the sample names in the sample.tsv file

# Import libraries
import os
import glob
import pandas as pd
from pathlib import Path

def load_sample_sheet(tsv_path: str, max_sample: int = None) -> pd.DataFrame:
    """
    Load the sample sheet from the config file
    """
    path = Path(tsv_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Sample sheet not found: {tsv_path}\n"
            f"Generate it with the generate_sample_sheet.py script."
        )
    
    df = pd.read_csv(path,sep="\t",dtype=str)

    # Validation of the file
    required_columns = {"sample","r1", "r2"}
    missing_columns = required_columns - set(df.columns)
    if missing_columns:
        raise ValueError(
            f"sample.tsv is missing columns: {missing_columns}\n"
            f"Required: sample, r1, r2"
        )

    # Drop empty rows
    df = df.dropna(subset=['sample','r1','r2'])

    # Apply max number of samples to be procesed
    if max_sample:
        df = df.iloc[:max_sample,:]
    
    return df

def get_fastq_samples(samples_dir, read1_suffix, read2_suffix):
    """
    Get the list of samples from the FASTQ Directory
    
    :param samples_dir: Path to the directory containing the fastq files
    :param read1_suffix: Suffix for R1 files (something like "_R1.fastq.gz")
    """

    # Reads all the 
    pattern = os.path.join(samples_dir, f"*{read1_suffix}")
    files = glob.glob(pattern)

    if not files:
        raise ValueError(
            f"No files found matching the patter: {pattern}\n"
            f"Check you samples_dir and read1_suffix in the config.yaml file."
        )   

    samples = []
    for file in files:
        #print(os.path.basename(file))
        basename = os.path.basename(file)
        sample_name = basename.replace(read1_suffix,"")
        #forward_read = file
        #reverse_read = os.path.join(samples_dir, f"{sample_name}{read2_suffix}")
        #samples.append([(forward_read,reverse_read)]) # For now we just retrun 5 samples to see if the pipeline is working.
        samples.append(sample_name)
    return samples

# Get only the read 1 for a sample
def get_sample_r1(sample_df:pd.DataFrame, sample:str) -> str:
    return sample_df.loc[sample,"r1"]

# Get only the read 2 for a sample
def get_sample_r2(sample_df:pd.DataFrame, sample:str) -> str:
    return sample_df.loc[sample,"r2"]

# Get all the names of the sample
def get_sample_names(sample_df: pd.DataFrame) -> str:
    return list(sample_df['sample'])

print(load_sample_sheet(
    tsv_path="/home/chandru/binp51/config/samples.tsv",
    max_sample=10
))

