# These are some of the common functions that the metagenomics pipeline uses
# load_sample_sheet : Load the entire sample sheet generated by the gnenrate_sample_sheet.py scrip
# get_fastq_samples: Get the samples from the data directory
# get_sample_r1: Get only the forward read for a sample id
# get_sample_r2: Get only the reverse read for a sample id
# get_sample_names: Get all the sample names in the sample.tsv file

# Import libraries
import os
import glob
import pandas as pd
from pathlib import Path

def load_sample_sheet(tsv_path: str, max_samples: int = None) -> pd.DataFrame:
    """
    Load the sample sheet from the config file
    """
    path = Path(tsv_path)
    if not path.exists():
        raise FileNotFoundError(
            f"Sample sheet not found: {tsv_path}\n"
            f"Generate it with the generate_sample_sheet.py script."
        )
    
    df = pd.read_csv(path,sep="\t",dtype=str)

    # Validation of the file
    required_columns = {"sample","r1", "r2"}
    missing_columns = required_columns - set(df.columns)
    if missing_columns:
        raise ValueError(
            f"sample.tsv is missing columns: {missing_columns}\n"
            f"Required: sample, r1, r2"
        )

    # Check if there exists both forward and reverse reads
    for _, row in df.iterrows():
        sample = row["sample"]
        r1 = row["r1"]
        r2 = row["r2"]

        if not Path(r1).exists() or not Path(r2).exists():
            raise FileNotFoundError(f"Missing a correct file path for {sample}")
    
    # Drop empty rows
    df = df.dropna(subset=['sample','r1','r2'])

    # Apply max number of samples to be procesed
    if max_samples:
        df = df.iloc[:max_samples,:]
    
    df = df.set_index("sample",drop=True)
    
    return df

# Get only the read 1 for a sample
def get_sample_r1(sample_df:pd.DataFrame, sample:str) -> str:
    return sample_df.loc[sample,"r1"]

# Get only the read 2 for a sample
def get_sample_r2(sample_df:pd.DataFrame, sample:str) -> str:
    return sample_df.loc[sample,"r2"]

# Get all the names of the sample
def get_sample_names(sample_df: pd.DataFrame) -> str:
    return list(sample_df.index)

#print(load_sample_sheet(
#    tsv_path="/home/chandru/binp51/config/samples.tsv",
#    max_samples=10
#))

#df = load_sample_sheet(
#    tsv_path="/home/chandru/binp51/config/samples.tsv",
#    max_samples=10
#)
#
#print(get_sample_names(df))
