location: swedencentral
resourceGroup: microbiome-rg
type: Microsoft.App/containerApps
name: microbiome-api
properties:
  managedEnvironmentId: /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/microbiome-rg/providers/Microsoft.App/managedEnvironments/microbiome-env
  configuration:
    ingress:
      external: true
      targetPort: 8000
    registries:
      - server: microbiomeacr.azurecr.io
        username: microbiomeacr
        passwordSecretRef: acr-password
    secrets:
      - name: acr-password
        value: <ACR_PASSWORD>
  template:
    scale:
      minReplicas: 1
      maxReplicas: 2
    volumes:
      - name: microbiome-data
        storageType: AzureFile
        storageName: microbiome-data
    containers:
      - name: microbiome-api
        image: microbiomeacr.azurecr.io/microbiome:latest
        command: ["uvicorn"]
        args: ["src.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
        volumeMounts:
          - volumeName: microbiome-data
            mountPath: /mnt/data
        env:
          - name: PYTHONPATH
            value: /app
          - name: ENV_FILE
            value: .env.azure
          - name: PROJECT_ROOT
            value: /app
          - name: UPLOAD_DIR
            value: /mnt/data/uploads
          - name: RESULTS_DIR
            value: /mnt/data/results
          - name: LOGS_DIR
            value: /mnt/data/logs
          - name: RUNTIME_DIR
            value: /mnt/data/runtime
          - name: BACKEND_DB_URL
            value: "postgresql://<PG_USER>:<PG_PASSWORD>@microbiome-postgres.postgres.database.azure.com:5432/malmo_db"
          - name: CELERY_BROKER_URL
            value: "redis://:<REDIS_PASSWORD>@20.91.202.193:6379/0"
          - name: CELERY_RESULT_BACKEND
            value: "redis://:<REDIS_PASSWORD>@20.91.202.193:6379/0"
          - name: SNAKEMAKE_PROFILE
            value: profiles/azure_batch
          - name: SNAKEMAKE_CONFIG
            value: config/config_single_run.yaml
          - name: SNAKEMAKE_BIN
            value: snakemake