# Metagenomics Pipeline Configuration

# Input files
samples_dir : "/lunarc/nobackup/projects/snic2019-34-3/shared_elhaik_lab1/Projects/Microbiome/Mixed2025/fastq_files"
output_dir : "results"

# File patterns
read1_suffix: "_R1.fastq.gz"
read2_suffix: "_R2.fastq.gz"

# Reference Databases
kraken2_db: "/home/chandru/myTMP/databases/bacteria_db" # This is the bacteria database


# Total Parameters

# fastp parameters


# Trimmomtic parameters


# Kraken2

# Bracken parameters



# Resource Allocation for each step

resources:
  fastqc:
    threads:
    mem_mb:
    time_min:
  
  fastp:
    threads:
    mem_mb:
    time_min:

  