# LUNARC production prfile for large-scale processing 
# Usage snakemake --profile profiles/lunarc --cores 200


cluster: "sbatch {cluster_params}"
cluster-status: "slurm-status.py"
cluster-cancel: "scancel"

# High settings
cores: 200 # Total cores across the cluster
jobs: 100  # Maximum number od concurrent SLURM jobs
max-jobs-per-second: 10
local-core: 4 # Cores for local rules


# Advanced job management
restart-time: 3
latency-wait: 60 
keep-going: true

# Cluster configuration file
cluser-config: "profiles/lunarc/cluter.yaml"

# SLURM integration
jobscript: "profiles/lunarc/jobscript.sh"

# Output and logging
printshellcmds: true
reason: true
show-failed-logs: true
log-level: "INFO"


