title: Microbiome Forensic Tracker
description: Predict geographical origin of environmental microbiome samples using machine learning.

remote_theme: just-the-docs/just-the-docs

url: "https://chandrashekarcr.github.io"
baseurl: "/microbiome-forensic-tracker"

repository_url: "https://github.com/ChandrashekarCR/microbiome-forensic-tracker"

color_scheme: dark
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

nav_enabled: true
aux_links:
  "GitHub Repository":
    - "https://github.com/ChandrashekarCR/microbiome-forensic-tracker"

footer_content: "Microbiome Forensic Tracker Documentation"

plugins:
  - jekyll-remote-theme